site_name: Macroalgae PISCES Module
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Model:
    - General Description: Model/model.md
    - Production: Model/Production.md
    - Remineralisation : Model/Remineralisation.md

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

extra_javascript:
  - js/mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML